### ISSUE TITLE
Switch to a more interesting code example

### ISSUE THREAD

**Issue by nahuelwexd** [vala-lang/vala-www#117]
The current code example simply creates an empty window. It would be nice to be able to show more interesting or useful code.

The GTK web site presents a code example that creates a window with a button, maybe it is a good reference.

**Comment by colinkiama** [comment]
The Vala code example featured here right?: https://www.gtk.org/

If so, that is a great idea!

**Comment by nahuelwexd** [comment]
Yeah, if we use the GTK example, it would look something like this (without the comments, with some grouping)

![](https://user-images.githubusercontent.com/18204745/176715023-3847c052-c62a-449a-8c2a-73b85b5a4081.png)

**Comment by rakshit087** [comment]
Looks good to me, shall I draft a PR?

**Comment by colinkiama** [comment]
Yeah
