### ISSUE TITLE
Code blocks with line numbers not closing tags properly

### ISSUE THREAD

**Issue by colinkiama** [vala-lang/vala-www#128]
This bug [has been fixed](https://github.com/getzola/zola/pull/1746) but a new release with the fix hasn't been released yet. As soon as that happens, the minimum required version of Zola in the README should be updated accordingly.

Note: Code blocks displays fine on the website but you will notice issues with formatting breaking on some RSS readers.

**Comment by colinkiama** [comment]
[New Zola version (0.16.0)](https://github.com/getzola/zola/releases) has been released. Time to test this out and custom themes

**Comment by rakshit087** [comment]
Is this bug fixed with the latest update?

**Comment by colinkiama** [comment]
Doesn't seem like it has. I would like to send a bug report but I need to verify if the issue might be caused by the Vala syntax file. (It doesn't highlight everything properly yet)

**Comment by colinkiama** [comment]
Line numbers are a "nice to have" at the moment but the site is completely fine without it.

This could be reopened if any major developments happen in the future.
