### ISSUE TITLE
Provide a Dockerfile and perhaps a devcontainer.json

### ISSUE THREAD

**Issue by nahuelwexd** [vala-lang/vala-www#139]

**Comment by rakshit087** [comment]
I was thinking of the same, but since it only has one requirement, is a docker container required?

**Comment by nahuelwexd** [comment]
> I was thinking of the same, but since it only has one requirement, is a docker container required?

Honestly what I was thinking is to be able to implement it in such a way to enable the GitHub Codespaces.

**Comment by rakshit087** [comment]
That's a good idea. Also, if I am forking this repo, I will be able to use Codespace for free right?

**Comment by colinkiama** [comment]
Would be able to adapt this dockerfile that uses a `debian-slim` image?

There are also official debian installation instructions here: https://github.com/shalzz/zola-deploy-action/blob/master/Dockerfile

**Comment by rakshit087** [comment]
I have started learning docker, will make a PR pretty soon :)

**Comment by lw64** [comment]
oops. Misunderstand what kind of docker container you mean. Nevermind me ;)
