### ISSUE TITLE
The example code is broken 

### ISSUE THREAD

**Issue by rakshit087** [vala-lang/vala-www#142]
I am not able to figure out the exact issue but, the code showcase is broken for me
![image](https://user-images.githubusercontent.com/50898928/177742418-048241b3-034f-4728-8c8a-d19d1a8415e9.png)

I also tried going back to a previous commit 
![image](https://user-images.githubusercontent.com/50898928/177742787-5c74b7dc-5233-48a9-a59b-7424f9294717.png)

I am on zola 0.15.3 is it because I am on  a Windows machine?

**Comment by colinkiama** [comment]
Yup. This is a known bug: https://github.com/getzola/zola/issues/1590

**Comment by colinkiama** [comment]
There are some other bugs with line numbers too. I don't think it's worth keeping them around until the next Zola update.

For now, I think that removing line numbers from all the whole site would be a good idea. (In Markdown code blocks, remove the `linenos` part).

**Comment by rakshit087** [comment]
Okay drafting a PR
