### ISSUE TITLE
Add hints to help reader compile code example

### ISSUE THREAD

**Issue by colinkiama** [vala-lang/vala-www#200]
The example should be changed into something that can run without any flags required.

Currently, this code example provides a bad first impression to new developers since the code seemingly doesn't work at all.

Any sort of "Hello World" program would be acceptable.

**Comment by Suzie97** [comment]
> The example should be changed into something that can run without any flags required.
> 
> Currently, this code example provides a bad first impression to new developers since the code seemingly doesn't work at all.
> 
> Any sort of "Hello World" program would be acceptable.

But the current sample also shows how easy it is to use gtk with Vala which imo is the main selling point of the language. Most people probably try out Vala for the same reason. This is debatable since we don't really have real data.

**Comment by colinkiama** [comment]
In that case, maybe comments should be added before the start of the code example letting people know:
1. Packages they need to install for the code to work
2. The compiler command they need to use for the code to compile successfully.

What do you all think?
