### ISSUE TITLE
Reduce the line-height of text across the whole site

### ISSUE THREAD

**Issue by colinkiama** [vala-lang/vala-www#201]
I interpreted the WCAG guidelines wrong. The user is the one who changes the line-height: https://www.w3.org/WAI/WCAG21/Understanding/text-spacing.html

Right now the paragraphs are fine but the  line-height for the other elements is way too big. There's too much space between each line.

**Comment by anubhav1206** [comment]
Can I work on it?

**Comment by colinkiama** [comment]
Sure.
