### ISSUE TITLE
Internal Docs

### ISSUE THREAD

**Issue by colinkiama** [vala-lang/vala-www#210]
Copy over documentation from [GNOME Vala Project Wiki](https://wiki.gnome.org/Projects/Vala/) to the website.

There will be some changes to the structure of the docs and some tweaks to the grammar to improve the reading experience however the content will remain the same (for now).

The sections to start with first are:
- Getting Started
- Vala Main Tutorial (and any samples that are referenced in the tutorial)
- Language Features and Introductory Samples
- GLib Samples

More docs can be added over time.

In https://github.com/vala-lang/vala-www/discussions/38, it was decided that the internal docs should be as part of a different subdomain (likely in a different repository too). So the work will be done away from this repository (unless something stops this from being possible).

**Comment by colinkiama** [comment]
GNOME Wiki is being retired so this is now a high-prioriry issue: https://hedgedoc.gnome.org/wiki-migration-guide

**Comment by Charadon** [comment]
Would it be possible to host something on a subdomain like wiki.vala.dev? Maybe using something like dokuwiki or mediawiki, or even static markdown. I don't think it'd be too difficult.

**Comment by colinkiama** [comment]
Repository: https://github.com/vala-lang/vala-docs
